
// Copyright © 2023 Sandro Dallo
//
// Use of this source code is governed by an BSD-style
// license that can be found in the LICENSE file.

// *****************************************************//
// AUTO GENERATED - DO NOT EDIT THIS FILE
// *****************************************************

export enum Icons {
   CogSolid = 'cog-solid', 
   MoonSolid = 'moon-solid', 
   MoonLine = 'moon-line', 
   SunSolid = 'sun-solid', 
   SunLine = 'sun-line', 
   AngleDoubleLine = 'angle-double-line' 
}